version: '3.7'

services:

  nginx:
    image: nginx:latest
    restart: always
    ports: 
      - "8080:80"
      - "443:443"
    volumes:
    - ./src/back:/var/www/html:rw
    - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    # - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
    networks: 
      - my_network
    labels:
      - traefik.enable=true
      - traefik.backend=back
      - traefik.frontend.rule=Host:app.localhost
    # environment:
    #   APACHE_DOCUMENT_ROOT: "public/"
    #   PHP_EXTENSION_XDEBUG: "1"
    #   PHP_INI_MEMORY_LIMIT: "1G"
    #   # Symfony
    #   APP_ENV: "dev"
    #   APP_SECRET: "8d2a5c935d8ef1c0e2b751147382bc75"
    #   DATABASE_URL: "mysql://$MYSQL_USER:$MYSQL_PASSWORD@mysql:3306/$MYSQL_DATABASE"
  
  php-fpm:
    extra_hosts: 
      - "host.docker.internal:host-gateway"
    build: ./docker/php
    container_name: php
    networks: 
      - my_network
    volumes: 
      - ./src/back:/var/www/html
    
  db:
    hostname: db
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: "$DB_ROOT_PASSWORD"
      MYSQL_DATABASE: "$DB_DATABASE"
      MYSQL_USER: "$DB_USER"
      MYSQL_PASSWORD: "$DB_PASSWORD"
    volumes:
      - db_data:/var/lib/mysql
      - ./services/mysql/utf8mb4.cnf:/etc/mysql/conf.d/utf8mb4.cnf:ro
    env_file: 
      - ./.env
    networks: 
      - my_network
      
volumes:
  db_data:
    driver: local

networks: 
  my_network:
    driver: bridge